### PR TITLE
Fix location of login.html file

### PR DESCRIPTION
**Pull request by nikhita**
`login.html` file needs to be copied because `pkg/handler/login.html` will only work locally. :/

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
@nikhita Did you ensure the `nobody` user can read that file?

**Comment by nikhita** [comment]
/hold

Let me check.

**Comment by nikhita** [comment]
> @nikhita Did you ensure the nobody user can read that file?

Updated and verified `nobody` can access it.

**Comment by nikhita** [comment]
Going to hold cancel here, will figure out the redirect url in another PR. This will at least give us basic auth functionality.

/hold cancel

**Pull request merged**
